### ISSUE TITLE
下载容易崩溃

### ISSUE THREAD

**Issue by xf110** [wes-lin/pierced-ngrok#1]
路由器是wr1200js，内网穿透后下载一个几十兆的文件客户端就蹦了，路由器可用内存只剩下几兆，arm版的也存在这个问题，盼修复！感谢大佬提供路由器版本

**Comment by wes-lin** [comment]
1.7版本的是存在这样的问题，然后作者也是直接放弃了，他是建议直接用2.0以上的版本，不过他是有提到解决方案[https://github.com/inconshreveable/ngrok/issues/109](url)
配置里加`inspect_addr: disabled`，然后运行参数加`-log=stdout`,不过我试了好像没啥作用，你可以蛮试试看。我也不是做go开发的，所以暂时也没法去修复，后面有空看看能不能学习下go。
